---
name: CI

on:  # NOLINT
  pull_request:
  push:
  schedule:
    - cron: '0 0 */2 * *'  # Every 2 days at midnight

jobs:
  test_docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gazebo-version: [11]
        # gazebo-version: [9, 11]
        # Define the Docker image(s) associated with each ROS distribution.
        # The include syntax allows additional variables to be defined, like
        # docker_image in this case. See documentation:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-configurations-in-a-matrix-build

        # Platforms are defined in REP 3, and REP 2000:
        # https://ros.org/reps/rep-0003.html
        # https://ros.org/reps/rep-2000.html
        include:
          # Foxy Fitzroy (May 2020 - May 2023)
          - docker_image: ros:foxy
            ros_distribution: foxy

    container: ${{ matrix.docker_image }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential clang cmake git wget libasio-dev libtinyxml2-dev lcov psmisc
          rosdep update
          sudo apt install -y python3-colcon-coveragepy-result
          sudo apt install -y python3-colcon-lcov-result

      - name: Install Gazebo
        run: |
          echo Installing Gazebo ${{ matrix.gazebo-version }}
          sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
          sudo apt update
          sudo apt install -y gazebo${{ matrix.gazebo-version }}
          sudo apt install -y libgazebo${{ matrix.gazebo-version }}-dev
          sudo apt install -y ros-${{ matrix.ros_distribution }}-gazebo-ros-pkgs

      - name: Install Dependencies
        run: |
          rosdep update
          rosdep install --from-paths src --ignore-src --rosdistro ${{ matrix.ros_distribution }} -y

      - name: Build Packages
        run: |
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh
          cd navio2_ros && catkin build && cd ..
          colcon build --packages-up-to blurr
